eval:
  dataset_module: InterHumanT2M
  mm_num_samples: 0 # 100
  mm_num_repeats: 30
  mm_num_times: 10
  diversity_times: 300
  replication_times: 20 # 20
  batch_size: 96
  cond_scale: 2.5
  history_length: 3
  sampling_timesteps: 50
  uncertainty_scale: 5.0
  scheduling_matrix_type: pyramid
  infer_from_velocity: False
  emb_scale: 6.0
  divide_by: 2.0

model:
  evaluator:
    NAME: InterCLIP
    NUM_LAYERS: 8
    NUM_HEADS: 8
    DROPOUT: 0.1
    INPUT_DIM: 258
    LATENT_DIM: 1024
    FF_SIZE: 2048
    ACTIVATION: gelu

    MOTION_REP: global
    FINETUNE: False
